
server:
  port: 5050
spring:
  application:
    name: config-server
    #本地仓库的git uri设置
  cloud:
    config:
      server:
        git:
          uri: fiel:///${user.dir}/src/main/resources/configs



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka