server:
  port: 6060
spring:
  application:
    name: zuul-server

  #暴露接口

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka




management:
  endpoints:
    web:
      exposure:
        include: env
