server:
  port: 6060
spring:
  application:
    name: zuul-server

zuul:
  routes:
    provider-server: /provider-server/**
    client-server: /client-server/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka


